import Head from "next/head";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/Dashboard.module.css";
import Feed from "../components/Feed";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard - FamilyHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles2.header}>
        <h1 className={styles2.h1}>FamilyHub</h1>
      </header>

      <main className={styles2.mainContainer}>
        <div className={`${styles2.dashboardNav} ${styles2.mainChild}`}>
          <h2>Profile picture</h2>
          <h2>Full name</h2>
          <p>
            <a href="#">Events</a>
          </p>
          <p>
            <a href="#">Photos</a>
          </p>
          <p>
            <a href="#">Recipes</a>
          </p>
        </div>
        <Feed />

        <div className={`${styles2.members} ${styles2.mainChild}`}>
          <h2>Family members</h2>
          <p>Member 1</p>
          <p>Member 2</p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
