import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/Dashboard.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashboard - FamilyHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles2.header}>
        <h1 className={styles2.h1}>FamilyHub</h1>
      </header>

      <main className={styles2.mainContainer}>
        <div className={`${styles2.dashboardNav} ${styles2.mainChild}`}>
          <h2>Profile picture</h2>
          <h2>Full name</h2>
          <p>Events</p>
          <p>Photos</p>
          <p>Recipes</p>
        </div>

        <div className={`${styles2.feed} ${styles2.mainChild}`}>
          <h2>Feed</h2>
          <div className={styles2.feedItem}>
            <p>
              <span className={styles2.feedItemPoster}>Example member</span>{" "}
              posted:
            </p>
            <p className={styles2.feedItemTime}>1 hr 12 m ago</p>
            <div className={styles2.feedItemBody}>
              <p>insert picture here</p>
              <p>Lorem ipsum...</p>
            </div>
          </div>
        </div>

        <div className={`${styles2.members} ${styles2.mainChild}`}>
          <h2>Family members</h2>
          <p>Member 1</p>
          <p>Member 2</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
